##############################
### ONLY FOR LOCAL TESTING ###
##############################
version: '3.1'

networks:
  smartprm:

services:
  smart_prm_api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    env_file: api/.env
    restart: always
    ports:
      - ${HTTP_PORT:-3080}:3080
    networks:
      - smartprm

  smart_prm_frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    restart: always
    ports:
      - ${HTTP_PORT:-8080}:8080
    environment:
      API_URL: "http://smart_prm_api:3080"
    networks:
      - smartprm
