##############################
### ONLY FOR LOCAL TESTING ###
##############################
version: '3.1'

networks:
  smartprm:

services:
  smartprm_api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    env_file: api/.env
    restart: always
    environment:
      APP_URL: "http://localhost:8085"
    ports:
      - ${HTTP_PORT:-3080}:3080
    networks:
      - smartprm

  smartprm_app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    restart: always
    ports:
      - ${HTTP_PORT:-8085}:80
    environment:
      API_URL: "http://localhost/api"
      VUE_APP_BASE_URL: http://localhost
    networks:
      - smartprm
